name: audit

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 45.118.132.204
          username: gold
          password: admin@123
          port: 22
          script: |
            export PATH=$PATH:/usr/local/go/bin && cd ci/wallet-meraki && git checkout develop && git pull && make compose_dev